### ISSUE TITLE
parameter name for hospitalization

### ISSUE THREAD

**Issue by davidchampredon** [phac-nml-phrsd/wem#16]
The model parameters `hosp.rate.t` and `hosp.rate.v` are _time-dependent_ multipliers of the parameter `hospital.prop`.  We should make those names consistent, like the other parameters of the same type. (I think `hosp.prop` and `hosp.prop.t/v` would be a good choice).

**Comment by ShokoofehNourbakhsh** [comment]
Fixed on the branch `stdr-hosp-name`
