### ISSUE TITLE
hospitalization rate as `broken_line()` (not `step_line()`)

### ISSUE THREAD

**Issue by davidchampredon** [phac-nml-phrsd/wem#17]
In `model.R` near line 163, change ` mmult = step_line(x=t, b = hosp.rate.t, v = hosp.rate.v)` into  mmult = broken_line(x=t, b = hosp.rate.t, v = hosp.rate.v) and at the same time, do not use a multiplicative factor, but just the value.

**Comment by ShokoofehNourbakhsh** [comment]
Fixed on the branch `stdr-hosp-name`
