### ISSUE TITLE
Separate waning immunity for V and R

### ISSUE THREAD

**Issue by davidchampredon** [phac-nml-phrsd/wem#19]
Currently we have only one parameter for waning immunity in both V and R compartments: `dur.immunity`. It is time dependent.

Create 2 new parameters, `dur.immunity.V` and `dur.immunity.R` to replace `dur.immunity` and make sure they are still time dependent.

**Comment by ShokoofehNourbakhsh** [comment]
Fixed on the branch `waning-immu-OM-2`. 

Note that branch `waning-immu-OM-1` gives **same** time-dependent  `dur.immunity` for both R and V.
